# Generated by Django 5.2.10 on 2026-02-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, db_column='UserID', help_text='User who made this payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.user'),
        ),
    ]
