# Generated by Django 5.2.10 on 2026-02-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_refactor_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='referraltransaction',
            name='RefTx_Code_User_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='Comments_PostID_a70532_idx',
            old_name='Comments_Post_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='Comments_AuthorI_8cc413_idx',
            old_name='Comments_Author_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='Coupons_Code_6ac383_idx',
            old_name='Coupon_Code_Active_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='Coupons_ValidFr_02d1ba_idx',
            old_name='Coupon_Valid_Range_idx',
        ),
        migrations.RenameIndex(
            model_name='couponusage',
            new_name='CouponUsage_CouponI_d4c4c5_idx',
            old_name='CouponUsage_Coupon_User_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationappeal',
            new_name='ModerationA_Status_517e49_idx',
            old_name='ModAppeal_Status_Created_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationappeal',
            new_name='ModerationA_UserID_4f8f49_idx',
            old_name='ModAppeal_User_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationqueue',
            new_name='ModerationQ_Status_998406_idx',
            old_name='ModQueue_Status_Created_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationqueue',
            new_name='ModerationQ_Content_991bdd_idx',
            old_name='ModQueue_Content_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationqueue',
            new_name='ModerationQ_Severit_00da26_idx',
            old_name='ModQueue_Severity_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='Posts_AuthorI_a29b81_idx',
            old_name='Posts_Author_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='Posts_Content_ec4e71_idx',
            old_name='Posts_Status_Created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='Posts_Content_d01774_idx',
            old_name='Posts_Type_Status_idx',
        ),
        migrations.RenameIndex(
            model_name='referralcode',
            new_name='ReferralCod_Code_a8c360_idx',
            old_name='RefCode_Code_Active_idx',
        ),
        migrations.RenameIndex(
            model_name='referralcode',
            new_name='ReferralCod_UserID_0ca1e6_idx',
            old_name='RefCode_User_Active_idx',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon_usage_id',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='referral_transaction_id',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='reward_amount',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='reward_given',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='usage_id',
            field=models.AutoField(db_column='UsageID', help_text='Unique identifier for the usage record', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referred_reward_amount',
            field=models.DecimalField(db_column='ReferredRewardAmount', decimal_places=2, default=0, help_text='Reward amount given to referred user', max_digits=10),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referred_rewarded',
            field=models.BooleanField(db_column='ReferredRewarded', default=False, help_text='Whether the referred user has received their reward'),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referrer_reward_amount',
            field=models.DecimalField(db_column='ReferrerRewardAmount', decimal_places=2, default=0, help_text='Reward amount given to referrer', max_digits=10),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='referrer_rewarded',
            field=models.BooleanField(db_column='ReferrerRewarded', default=False, help_text='Whether the referrer has received their reward'),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='transaction_id',
            field=models.AutoField(db_column='TransactionID', help_text='Unique identifier for the referral transaction', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_column='AuthorID', help_text='User who authored the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(db_column='CommentID', help_text='Unique identifier for the comment', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flagged', 'Flagged'), ('removed', 'Removed'), ('under_review', 'Under Review')], db_column='ContentStatus', default='published', help_text='Content moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_text',
            field=models.TextField(db_column='ContentText', help_text='The text content to be moderated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderated_at',
            field=models.DateTimeField(blank=True, db_column='ModeratedAt', help_text='When the content was last moderated', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation_notes',
            field=models.TextField(blank=True, db_column='ModerationNotes', help_text='Notes from moderation', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, db_column='ParentCommentID', help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='PostID', help_text='Post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='Plans this coupon applies to (empty = all plans)', related_name='coupons', to='myapp.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_column='Code', help_text='Unique coupon code (e.g., WELCOME20)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.AutoField(db_column='CouponID', help_text='Unique identifier for the coupon', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='current_uses',
            field=models.IntegerField(db_column='CurrentUses', default=0, help_text='Number of times this coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, db_column='Description', default='', help_text='Human-readable description of the coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], db_column='DiscountType', help_text='Type of discount: percentage or fixed amount', max_length=12),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(db_column='DiscountValue', decimal_places=2, help_text='Discount amount (percentage 0-100 or fixed dollar amount)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='first_purchase_only',
            field=models.BooleanField(db_column='FirstPurchaseOnly', default=False, help_text='Whether this coupon is only valid for first-time purchases'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(db_column='MaxUses', default=0, help_text='Maximum total uses (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.IntegerField(db_column='MaxUsesPerUser', default=1, help_text='Maximum uses per user (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, db_column='MinPurchaseAmount', decimal_places=2, help_text='Minimum purchase amount required to use this coupon', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(db_column='ValidFrom', help_text='When the coupon becomes valid'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(db_column='ValidUntil', help_text='When the coupon expires'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(db_column='CouponID', help_text='Coupon that was used', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='myapp.coupon'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='discount_applied',
            field=models.DecimalField(db_column='DiscountApplied', decimal_places=2, help_text='Actual discount amount applied', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='final_amount',
            field=models.DecimalField(db_column='FinalAmount', decimal_places=2, help_text='Final amount after discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='original_amount',
            field=models.DecimalField(db_column='OriginalAmount', decimal_places=2, help_text='Original amount before discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(db_column='UserID', help_text='User who used the coupon', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='moderation_appeal_id',
            field=models.AutoField(db_column='ModerationAppealID', help_text='Unique identifier for the appeal', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='original_queue',
            field=models.ForeignKey(db_column='OriginalQueueID', help_text='The original moderation queue item being appealed', on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='myapp.moderationqueue'),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='reason',
            field=models.TextField(db_column='Reason', help_text='Reason for the appeal'),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_column='ReviewedAt', help_text='When the appeal was reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_column='ReviewerID', help_text='Admin/moderator who reviewed the appeal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='reviewer_notes',
            field=models.TextField(blank=True, db_column='ReviewerNotes', help_text='Notes from the reviewer', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_column='Status', default='pending', help_text='Current appeal status', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='moderationappeal',
            name='user',
            field=models.ForeignKey(db_column='UserID', help_text='User submitting the appeal', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='auto_flag_reason',
            field=models.TextField(blank=True, db_column='AutoFlagReason', help_text='Reason from automated moderation system', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='auto_flagged',
            field=models.BooleanField(db_column='AutoFlagged', default=False, help_text='Whether this was flagged by automated moderation'),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='content_id',
            field=models.IntegerField(db_column='ContentID', help_text='ID of the content being moderated'),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='content_type',
            field=models.CharField(db_column='ContentType', help_text='Type of content being moderated (e.g., post, comment, profile)', max_length=50),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='details',
            field=models.TextField(blank=True, db_column='Details', default='', help_text='Additional details about the report'),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='moderated_at',
            field=models.DateTimeField(blank=True, db_column='ModeratedAt', help_text='When the content was moderated', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='moderation_notes',
            field=models.TextField(blank=True, db_column='ModerationNotes', help_text='Notes from the moderator', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='moderation_queue_id',
            field=models.AutoField(db_column='ModerationQueueID', help_text='Unique identifier for the moderation queue entry', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='moderator_id',
            field=models.ForeignKey(blank=True, db_column='ModeratorID', help_text='Moderator who handled this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='reason',
            field=models.TextField(db_column='Reason', help_text='Reason for the report/flag'),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='reporter_id',
            field=models.ForeignKey(blank=True, db_column='ReporterID', help_text='User who reported the content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='severity',
            field=models.IntegerField(db_column='Severity', default=1, help_text='Severity level (1=low, 5=critical)'),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('changes_requested', 'Changes Requested')], db_column='Status', default='pending', help_text='Current moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='moderationqueue',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED'), ('Refunded', 'REFUNDED'), ('Partial', 'PARTIALLY_REFUNDED')], db_column='Status', help_text='Payment processing status', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='AuthorID', help_text='User who created the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('flagged', 'Flagged'), ('removed', 'Removed'), ('under_review', 'Under Review')], db_column='ContentStatus', default='published', help_text='Content moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=models.TextField(db_column='ContentText', help_text='The text content to be moderated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(db_column='ContentType', default='general', help_text='Type of post (article, update, discussion, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderated_at',
            field=models.DateTimeField(blank=True, db_column='ModeratedAt', help_text='When the content was last moderated', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderation_notes',
            field=models.TextField(blank=True, db_column='ModerationNotes', help_text='Notes from moderation', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(db_column='PostID', help_text='Unique identifier for the post', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_column='Title', help_text='Post title', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(db_column='Code', help_text='Unique referral code string', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='current_uses',
            field=models.IntegerField(db_column='CurrentUses', default=0, help_text='Number of times this code has been used'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_column='ExpiresAt', help_text='When this referral code expires (null = never)', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='max_uses',
            field=models.IntegerField(db_column='MaxUses', default=0, help_text='Maximum times this code can be used (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referral_code_id',
            field=models.AutoField(db_column='ReferralCodeID', help_text='Unique identifier for the referral code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='reward_amount',
            field=models.DecimalField(db_column='RewardAmount', decimal_places=2, default=0, help_text='Amount of reward ($ for credit, % for discount, days for free month)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='reward_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('discount', 'Discount'), ('free_month', 'Free Month'), ('feature_unlock', 'Feature Unlock')], db_column='RewardType', default='credit', help_text='Type of reward given for successful referral', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(db_column='UserID', help_text='User who owns this referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='CreatedBy', help_text='ID of the user who created this record', null=True),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='is_active',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, help_text='Flag indicating if the record is active (1=active, 0=inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='is_deleted',
            field=models.IntegerField(blank=True, db_column='IsDeleted', default=0, help_text='Flag indicating if the record is soft-deleted (1=deleted, 0=not deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='referral_code',
            field=models.ForeignKey(db_column='ReferralCodeID', help_text='Referral code that was used', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='myapp.referralcode'),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='referred_user',
            field=models.ForeignKey(db_column='ReferredUserID', help_text='New user who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Timestamp when the record was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='UpdatedBy', help_text='ID of the user who last updated this record', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature_tier_1',
            field=models.BooleanField(db_column='AIPredictionsEnabled', default=False, help_text='Whether tier-1 premium features are enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature_tier_2',
            field=models.BooleanField(db_column='AdvancedIndicatorsEnabled', default=False, help_text='Whether tier-2 premium features are enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='feature_tier_3',
            field=models.BooleanField(db_column='PortfolioTracking', default=False, help_text='Whether tier-3 premium features are enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_operations',
            field=models.IntegerField(db_column='MaxExchanges', default=1, help_text='Maximum number of operations allowed per period'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='PasswordHash', help_text='Hashed password', max_length=255),
        ),
        migrations.AddIndex(
            model_name='referraltransaction',
            index=models.Index(fields=['referral_code', 'created_at'], name='ReferralTra_Referra_cc1ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransaction',
            index=models.Index(fields=['referred_user'], name='ReferralTra_Referre_74a2f9_idx'),
        ),
    ]
