# Generated by Django 5.2.10 on 2026-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_referraltransaction_reftx_code_user_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feature_tier_1',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feature_tier_2',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feature_tier_3',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, db_column='FCMToken', help_text='Firebase Cloud Messaging token for push notifications', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(db_column='PreferredLanguage', default='en', help_text="User's preferred language code (e.g., 'en', 'es', 'fr')", max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CreditCard', 'CREDIT CARD'), ('DebitCard', 'DEBIT CARD'), ('PayPal', 'PAYPAL'), ('BankTransfer', 'BANK TRANSFER'), ('Crypto', 'CRYPTO'), ('ApplePay', 'APPLE PAY'), ('GooglePay', 'GOOGLE PAY')], db_column='PaymentMethod', help_text='Method used for payment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Processing', 'PROCESSING'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED'), ('Cancelled', 'CANCELLED'), ('Refunded', 'REFUNDED'), ('Partial', 'PARTIALLY_REFUNDED')], db_column='Status', help_text='Payment processing status', max_length=20, null=True),
        ),
    ]
